from db import Base
from sqlalchemy import Column, Integer, String



class Film(Base):
    __tablename__ = "films"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String)
    director = Column(String)





HARD_CODED_FILMS = [ # a total of 200 films
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
    {'name':'Halland City', 'director':'Mr Peabuddy'},
    {'name':'Fast and furious 2', 'director':'Joe Simpson'},
    {'name':'Fast and furious 3', 'director':'Joe Simpson'},
    {'name':'Fast and furious 4', 'director':'Joe Simpson'},
    {'name':'Fast and furious 5', 'director':'Joe Simpson'},
    {'name':'Fast and furious 6', 'director':'Joe Simpson'},
    {'name':'Fast and furious 7', 'director':'Joe Simpson'},
    {'name':'Fast and furious 8', 'director':'Joe Simpson'},
    {'name':'Fast and furious 9', 'director':'Joe Simpson'},
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
    {'name':'Halland City', 'director':'Mr Peabuddy'},
    {'name':'Fast and furious 2', 'director':'Joe Simpson'},
    {'name':'Fast and furious 3', 'director':'Joe Simpson'},
    {'name':'Fast and furious 4', 'director':'Joe Simpson'},
    {'name':'Fast and furious 5', 'director':'Joe Simpson'},
    {'name':'Fast and furious 6', 'director':'Joe Simpson'},
    {'name':'Fast and furious 7', 'director':'Joe Simpson'},
    {'name':'Fast and furious 8', 'director':'Joe Simpson'},
    {'name':'Fast and furious 9', 'director':'Joe Simpson'},
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
    {'name':'Halland City', 'director':'Mr Peabuddy'},
    {'name':'Fast and furious 2', 'director':'Joe Simpson'},
    {'name':'Fast and furious 3', 'director':'Joe Simpson'},
    {'name':'Fast and furious 4', 'director':'Joe Simpson'},
    {'name':'Fast and furious 5', 'director':'Joe Simpson'},
    {'name':'Fast and furious 6', 'director':'Joe Simpson'},
    {'name':'Fast and furious 7', 'director':'Joe Simpson'},
    {'name':'Fast and furious 8', 'director':'Joe Simpson'},
    {'name':'Fast and furious 9', 'director':'Joe Simpson'},
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
    {'name':'Halland City', 'director':'Mr Peabuddy'},
    {'name':'Fast and furious 2', 'director':'Joe Simpson'},
    {'name':'Fast and furious 3', 'director':'Joe Simpson'},
    {'name':'Fast and furious 4', 'director':'Joe Simpson'},
    {'name':'Fast and furious 5', 'director':'Joe Simpson'},
    {'name':'Fast and furious 6', 'director':'Joe Simpson'},
    {'name':'Fast and furious 7', 'director':'Joe Simpson'},
    {'name':'Fast and furious 8', 'director':'Joe Simpson'},
    {'name':'Fast and furious 9', 'director':'Joe Simpson'},
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
    {'name':'Halland City', 'director':'Mr Peabuddy'},
    {'name':'Fast and furious 2', 'director':'Joe Simpson'},
    {'name':'Fast and furious 3', 'director':'Joe Simpson'},
    {'name':'Fast and furious 4', 'director':'Joe Simpson'},
    {'name':'Fast and furious 5', 'director':'Joe Simpson'},
    {'name':'Fast and furious 6', 'director':'Joe Simpson'},
    {'name':'Fast and furious 7', 'director':'Joe Simpson'},
    {'name':'Fast and furious 8', 'director':'Joe Simpson'},
    {'name':'Fast and furious 9', 'director':'Joe Simpson'},
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
    {'name':'Halland City', 'director':'Mr Peabuddy'},
    {'name':'Fast and furious 2', 'director':'Joe Simpson'},
    {'name':'Fast and furious 3', 'director':'Joe Simpson'},
    {'name':'Fast and furious 4', 'director':'Joe Simpson'},
    {'name':'Fast and furious 5', 'director':'Joe Simpson'},
    {'name':'Fast and furious 6', 'director':'Joe Simpson'},
    {'name':'Fast and furious 7', 'director':'Joe Simpson'},
    {'name':'Fast and furious 8', 'director':'Joe Simpson'},
    {'name':'Fast and furious 9', 'director':'Joe Simpson'},
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
    {'name':'Halland City', 'director':'Mr Peabuddy'},
    {'name':'Fast and furious 2', 'director':'Joe Simpson'},
    {'name':'Fast and furious 3', 'director':'Joe Simpson'},
    {'name':'Fast and furious 4', 'director':'Joe Simpson'},
    {'name':'Fast and furious 5', 'director':'Joe Simpson'},
    {'name':'Fast and furious 6', 'director':'Joe Simpson'},
    {'name':'Fast and furious 7', 'director':'Joe Simpson'},
    {'name':'Fast and furious 8', 'director':'Joe Simpson'},
    {'name':'Fast and furious 9', 'director':'Joe Simpson'},
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
    {'name':'Halland City', 'director':'Mr Peabuddy'},
    {'name':'Fast and furious 2', 'director':'Joe Simpson'},
    {'name':'Fast and furious 3', 'director':'Joe Simpson'},
    {'name':'Fast and furious 4', 'director':'Joe Simpson'},
    {'name':'Fast and furious 5', 'director':'Joe Simpson'},
    {'name':'Fast and furious 6', 'director':'Joe Simpson'},
    {'name':'Fast and furious 7', 'director':'Joe Simpson'},
    {'name':'Fast and furious 8', 'director':'Joe Simpson'},
    {'name':'Fast and furious 9', 'director':'Joe Simpson'},
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
    {'name':'Halland City', 'director':'Mr Peabuddy'},
    {'name':'Fast and furious 2', 'director':'Joe Simpson'},
    {'name':'Fast and furious 3', 'director':'Joe Simpson'},
    {'name':'Fast and furious 4', 'director':'Joe Simpson'},
    {'name':'Fast and furious 5', 'director':'Joe Simpson'},
    {'name':'Fast and furious 6', 'director':'Joe Simpson'},
    {'name':'Fast and furious 7', 'director':'Joe Simpson'},
    {'name':'Fast and furious 8', 'director':'Joe Simpson'},
    {'name':'Fast and furious 9', 'director':'Joe Simpson'},
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
    {'name':'Halland City', 'director':'Mr Peabuddy'},
    {'name':'Fast and furious 2', 'director':'Joe Simpson'},
    {'name':'Fast and furious 3', 'director':'Joe Simpson'},
    {'name':'Fast and furious 4', 'director':'Joe Simpson'},
    {'name':'Fast and furious 5', 'director':'Joe Simpson'},
    {'name':'Fast and furious 6', 'director':'Joe Simpson'},
    {'name':'Fast and furious 7', 'director':'Joe Simpson'},
    {'name':'Fast and furious 8', 'director':'Joe Simpson'},
    {'name':'Fast and furious 9', 'director':'Joe Simpson'},
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
    {'name':'Halland City', 'director':'Mr Peabuddy'},
    {'name':'Fast and furious 2', 'director':'Joe Simpson'},
    {'name':'Fast and furious 3', 'director':'Joe Simpson'},
    {'name':'Fast and furious 4', 'director':'Joe Simpson'},
    {'name':'Fast and furious 5', 'director':'Joe Simpson'},
    {'name':'Fast and furious 6', 'director':'Joe Simpson'},
    {'name':'Fast and furious 7', 'director':'Joe Simpson'},
    {'name':'Fast and furious 8', 'director':'Joe Simpson'},
    {'name':'Fast and furious 9', 'director':'Joe Simpson'},
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
    {'name':'Halland City', 'director':'Mr Peabuddy'},
    {'name':'Fast and furious 2', 'director':'Joe Simpson'},
    {'name':'Fast and furious 3', 'director':'Joe Simpson'},
    {'name':'Fast and furious 4', 'director':'Joe Simpson'},
    {'name':'Fast and furious 5', 'director':'Joe Simpson'},
    {'name':'Fast and furious 6', 'director':'Joe Simpson'},
    {'name':'Fast and furious 7', 'director':'Joe Simpson'},
    {'name':'Fast and furious 8', 'director':'Joe Simpson'},
    {'name':'Fast and furious 9', 'director':'Joe Simpson'},
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
    {'name':'Halland City', 'director':'Mr Peabuddy'},
    {'name':'Fast and furious 2', 'director':'Joe Simpson'},
    {'name':'Fast and furious 3', 'director':'Joe Simpson'},
    {'name':'Fast and furious 4', 'director':'Joe Simpson'},
    {'name':'Fast and furious 5', 'director':'Joe Simpson'},
    {'name':'Fast and furious 6', 'director':'Joe Simpson'},
    {'name':'Fast and furious 7', 'director':'Joe Simpson'},
    {'name':'Fast and furious 8', 'director':'Joe Simpson'},
    {'name':'Fast and furious 9', 'director':'Joe Simpson'},
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
    {'name':'Halland City', 'director':'Mr Peabuddy'},
    {'name':'Fast and furious 2', 'director':'Joe Simpson'},
    {'name':'Fast and furious 3', 'director':'Joe Simpson'},
    {'name':'Fast and furious 4', 'director':'Joe Simpson'},
    {'name':'Fast and furious 5', 'director':'Joe Simpson'},
    {'name':'Fast and furious 6', 'director':'Joe Simpson'},
    {'name':'Fast and furious 8', 'director':'Joe Simpson'},
    {'name':'Fast and furious 9', 'director':'Joe Simpson'},
    {'name':'Blade Runner', 'director':'Ridley Scott'},
    {'name':'Pulp Fiction', 'director':'Quentin Tarantino'},
    {'name':'Mulholland Drive', 'director':'David Lynch'},
    {'name':'Fast and furious 1', 'director':'Joe Simpson'},
    {'name':'Les Dalton', 'director':'Avrel Dalton'},
]
